**Домашнее задание №1**

Создание массивов

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

zeros = np.zeros((3, 4))

ones = np.ones((2, 3))

full_8 = np.full((2, 2), 8) 

identity = np.eye(3) #массив из единичной матрицы

range_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)

random_arr = np.random.random((3, 3))  # случайные числа из [0,1)
randint_arr = np.random.randint(0, 10, (2, 4))  #случайные целые числа из [0,10)

Shape и dtype

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Массив:")
print(arr)
print(f"Shape: {arr.shape}")
print(f"Размерность: {arr.ndim}")
print(f"Количество элементов: {arr.size}")
print(f"Тип данных: {arr.dtype}")

Массив:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Размерность: 2
Количество элементов: 6
Тип данных: int32


In [7]:
#изменение формы массива (reshape)
reshaped = arr.reshape(3, 2)
print("\nПосле reshape(3, 2):")
print(reshaped)


После reshape(3, 2):
[[1 2]
 [3 4]
 [5 6]]


In [8]:
int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1, 2, 3], dtype=np.float64)
bool_arr = np.array([True, False, True])

print(f"Типы данных:")
print(f"int32: {int_arr.dtype}")
print(f"float64: {float_arr.dtype}")
print(f"bool: {bool_arr.dtype}")

#преобразование типов данных
converted = float_arr.astype(np.int32)
print(f"После преобразования: {converted.dtype}")

Типы данных:
int32: int32
float64: float64
bool: bool
После преобразования: int32


Индексирование и срезы

In [10]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
#индексирование
print("Индексирование")
print(f"arr[0, 1] = {arr[0, 1]}")
print(f"arr[2, 3] = {arr[2, 3]}")

#срезы
print("\nСрезы:")
print("arr[0:2, 1:3]:")  #первые 2 строки, столбцы 1-2
arr[0:2, 1:3]

print("arr[:, 1:3]:")   #все строки, столбцы 1-2
arr[:, 1:3]

print("arr[1:, :]:")    #со второй строки до конца, все столбцы
print(arr[1:, :])

print("\nС шагом 2:")
print(arr[::2, ::2])  #каждая вторая строка и столбец

rows = np.array([0, 1, 2])
cols = np.array([1, 2, 3])
print(f"\nИндексирование массивами: {arr[rows, cols]}")  # [2, 7, 12]

print("\nБулево индексирование")
bool_mask = arr > 5
print("Маска для значений > 5:")
print(bool_mask)
print("Значения > 5:", arr[bool_mask])

Индексирование
arr[0, 1] = 2
arr[2, 3] = 12

Срезы:
arr[0:2, 1:3]:
arr[:, 1:3]:
arr[1:, :]:
[[ 5  6  7  8]
 [ 9 10 11 12]]

С шагом 2:
[[ 1  3]
 [ 9 11]]

Индексирование массивами: [ 2  7 12]

Булево индексирование
Маска для значений > 5:
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
Значения > 5: [ 6  7  8  9 10 11 12]


Простые операции над массивами

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Арифметические операции:")
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"b / a = {b / a}")
print(f"a ** 2 = {a ** 2}")

print(f"\nОперации с числом:")
print(f"a + 10 = {a + 10}")
print(f"a * 2 = {a * 2}")

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print("\nМатричные операции:")
print("Поэлементное умножение:")
print(matrix1 * matrix2)

print("Матричное умножение:")
print(np.dot(matrix1, matrix2))

arr = np.array([1, 4, 9, 16])
print(f"\nМатематические функции:")
print(f"np.sqrt(arr) = {np.sqrt(arr)}")
print(f"np.cos(arr) = {np.cos(arr)}")
print(f"np.exp(arr) = {np.exp(arr)}")

Арифметические операции:
a + b = [11 22 33 44]
a - b = [ -9 -18 -27 -36]
a * b = [ 10  40  90 160]
b / a = [10. 10. 10. 10.]
a ** 2 = [ 1  4  9 16]

Операции с числом:
a + 10 = [11 12 13 14]
a * 2 = [2 4 6 8]

Матричные операции:
Поэлементное умножение:
[[ 5 12]
 [21 32]]
Матричное умножение:
[[19 22]
 [43 50]]

Математические функции:
np.sqrt(arr) = [1. 2. 3. 4.]
np.cos(arr) = [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
np.exp(arr) = [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


Статистики

In [15]:
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
print(data)

print(f"\nБазовые статистики:")
print(f"Сумма всех элементов: {np.sum(data)}")
print(f"Среднее значение: {np.mean(data)}")
print(f"Медиана: {np.median(data)}")
print(f"Стандартное отклонение: {np.std(data)}")
print(f"Дисперсия: {np.var(data)}")
print(f"Минимальное значение: {np.min(data)}")
print(f"Максимальное значение: {np.max(data)}")

print(f"\nСтатистики по строкам:")
print(f"Суммы по строкам: {np.sum(data, axis=1)}")
print(f"Средние по строкам: {np.mean(data, axis=1)}")

print(f"\nСтатистики по столбцам:")
print(f"Суммы по столбцам: {np.sum(data, axis=0)}")
print(f"Средние по столбцам: {np.mean(data, axis=0)}")

print(f"\nДоп. статистики:")
print(f"Процентили 25%, 50%, 75%: {np.percentile(data, [25, 50, 75])}")
print(f"Кумулятивная сумма: {np.cumsum(data)}")
print(f"Произведение элементов: {np.prod(data)}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Базовые статистики:
Сумма всех элементов: 78
Среднее значение: 6.5
Медиана: 6.5
Стандартное отклонение: 3.452052529534663
Дисперсия: 11.916666666666666
Минимальное значение: 1
Максимальное значение: 12

Статистики по строкам:
Суммы по строкам: [10 26 42]
Средние по строкам: [ 2.5  6.5 10.5]

Статистики по столбцам:
Суммы по столбцам: [15 18 21 24]
Средние по столбцам: [5. 6. 7. 8.]

Доп. статистики:
Процентили 25%, 50%, 75%: [3.75 6.5  9.25]
Кумулятивная сумма: [ 1  3  6 10 15 21 28 36 45 55 66 78]
Произведение элементов: 479001600


In [16]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
print(f"\nКорреляция x и y: {np.corrcoef(x, y)[0, 1]}")
print(f"Ковариация x и y: {np.cov(x, y)[0, 1]}")


Корреляция x и y: 0.9999999999999999
Ковариация x и y: 5.0
